#!/usr/bin/env python3
"""Write data/use-cases.json. Edit this file, then run it, then render_readme.py."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHECKED = "2026-09-17"


def src(url, typ, verified, author=None, date=None):
    item = {"url": url, "type": typ, "what_verified": verified}
    if author:
        item["author"] = author
    if date:
        item["date"] = date
    return item


def entry(**kwargs):
    kwargs.setdefault("other_components", [])
    kwargs.setdefault("skill_frameworks", [])
    kwargs.setdefault("repo_url", None)
    kwargs.setdefault("demo_url", None)
    kwargs.setdefault("install_url", None)
    kwargs.setdefault("last_checked", CHECKED)
    kwargs.setdefault("highlight", False)
    return kwargs


ENTRIES = [
    entry(
        id="jev-ultrafast",
        title="Jev Ultrafast browser agent",
        category="action-taking",
        highlight=True,
        short_description="Indexed DOM action space: Jev picks the operation and target; a small LLM only types text.",
        actual_actions_or_outcome="Drives Chrome through a local inspector; README documents a Google Flights search example. Does not book flights.",
        jev_role="Choice of operation plus speculative target questions in one request",
        other_components=["browser-harness", "Chrome remote debugging", "separate text model"],
        origin="community",
        evidence_level="demo-inspected",
        sources=[
            src("https://github.com/browser-use/jev-ultrafast", "repo", "README loop, examples/flights.py, 2247 stars on 2026-09-17", "browser-use", "2026-09-18"),
        ],
        repo_url="https://github.com/browser-use/jev-ultrafast",
        demo_url="https://github.com/browser-use/jev-ultrafast/blob/main/docs/demo.mp4",
        install_url="https://github.com/browser-use/jev-ultrafast#try-it",
        caveats="Timing/cost claims in the README were not remeasured. Jev is text-only; the page is serialized to text/DOM, not pixels.",
        readiness="runnable-from-readme",
    ),
    entry(
        id="typesafe-mario",
        title="TypeSafe Mario",
        category="action-taking",
        highlight=True,
        short_description="Jev chooses NES controller macros from structured emulator RAM JSON, not screenshots.",
        actual_actions_or_outcome="Local play loop writes run JSONL; dashboard shows action distribution.",
        jev_role="Choice over legal controller actions",
        other_components=["NES emulator", "user-supplied ROM"],
        origin="community",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/fhshaik/typesafe-mario", "repo", "README architecture and action set", "fhshaik", "2026-09-16"),
        ],
        repo_url="https://github.com/fhshaik/typesafe-mario",
        install_url="https://github.com/fhshaik/typesafe-mario#setup",
        caveats="ROM is not in the repo. Interactive demo, not a shipped product. No native vision.",
        readiness="runnable-from-readme",
    ),
    entry(
        id="typesafe-computer-use",
        title="TypeSafe Computer Use",
        category="action-taking",
        highlight=True,
        short_description="OCR a Mac screen, then Jev chooses the next UI action and code clicks.",
        actual_actions_or_outcome="Local screenshot → OCR → Choice/Noul → OS action loop.",
        jev_role="Action selection on OCR text state",
        other_components=["OCR", "macOS automation", "typesafe_sdk"],
        origin="community",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/awlevin/typesafe-computer-use", "repo", "API description plus typesafe_sdk imports; 168 stars 2026-09-17", "awlevin", "2026-09-17"),
        ],
        repo_url="https://github.com/awlevin/typesafe-computer-use",
        install_url="https://github.com/awlevin/typesafe-computer-use",
        caveats="Not native vision. Per-step cost in the GitHub description is an author claim.",
        readiness="runnable-from-readme",
    ),
    entry(
        id="jev-review",
        title="Jev Review",
        category="action-taking",
        highlight=True,
        short_description="Staged Jev judgments over git diffs or a codebase, with a local dashboard.",
        actual_actions_or_outcome="JSON reports plus dashboard on 127.0.0.1:4317. Does not publish reviews remotely.",
        jev_role="Noul risk matrix, Choice/Score file profiles, evidence selection, severity routing",
        other_components=["Node", "Git"],
        origin="community",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/devagrawal09/jev-review", "repo", "README workflow and commands", "devagrawal09", "2026-09-17"),
        ],
        repo_url="https://github.com/devagrawal09/jev-review",
        install_url="https://github.com/devagrawal09/jev-review#quick-start",
        caveats="Developer tool, not a hosted CI product. Thresholds are code policy.",
        readiness="runnable-from-readme",
    ),
    entry(
        id="pg-jev",
        title="pg-jev",
        category="action-taking",
        highlight=True,
        short_description="PostgreSQL extension: natural-language WHERE / ORDER / classify via Jev over row composites.",
        actual_actions_or_outcome="SQL helpers call TypeSafe; rows that match a Noul/Choice/Score filter are returned by the database.",
        jev_role="Batched parallel Noul/Choice/Score per row",
        other_components=["PostgreSQL 14–17", "plpython3u"],
        origin="community",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/realZachi/pg-jev", "repo", "README SQL API and install notes", "realZachi", "2026-09-17"),
        ],
        repo_url="https://github.com/realZachi/pg-jev",
        install_url="https://github.com/realZachi/pg-jev#install",
        caveats="Needs untrusted plpython3u / superuser. Row text is sent to TypeSafe. Latency numbers in README not re-run.",
        readiness="installable-from-source",
    ),
    entry(
        id="pi-warden",
        title="pi-warden",
        category="action-taking",
        highlight=True,
        short_description="Guardrails for the Pi coding agent: Jev judges irreversible or off-task tool calls before they run.",
        actual_actions_or_outcome="Steers or blocks Pi tool calls; published as a pi.dev package.",
        jev_role="Judgments on proposed tool calls, stuck loops, unverified done claims",
        other_components=["Pi agent", "pi-typesafe"],
        origin="community",
        evidence_level="demo-inspected",
        sources=[
            src("https://github.com/DevMortimer/pi-warden", "repo", "GitHub description and repo exist; 44 stars 2026-09-17", "DevMortimer", "2026-09-18"),
            src("https://pi.dev/packages/pi-warden", "docs", "Package page extracted in Reddit lane", "pi.dev", "2026-09-17"),
        ],
        repo_url="https://github.com/DevMortimer/pi-warden",
        install_url="https://pi.dev/packages/pi-warden",
        caveats="Did not re-run against a live Pi session.",
        readiness="installable",
    ),
    entry(
        id="foreman",
        title="Foreman",
        category="action-taking",
        short_description="Software-factory supervisor that uses the official Python SDK to judge worker steps.",
        actual_actions_or_outcome="Semantic supervision of coding workers (per README/description).",
        jev_role="Noul/judgments via AsyncTypeSafeClient",
        other_components=["Codex workers"],
        origin="community",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/thruwire/foreman", "repo", "typesafe_sdk imports; 199 stars 2026-09-17", "thruwire", "2026-09-17"),
        ],
        repo_url="https://github.com/thruwire/foreman",
        install_url="https://github.com/thruwire/foreman",
        caveats="Full README walkthrough was partial; grounded on import evidence and description.",
        readiness="inspect-further",
    ),
    entry(
        id="beadsort",
        title="beadsort",
        category="action-taking",
        short_description="Jev labels beads issues: typed, calibrated backlog labels.",
        actual_actions_or_outcome="Writes labels onto beads items from issue text.",
        jev_role="Classification / labeling Choice or Noul over issue state",
        other_components=["beads"],
        origin="community",
        evidence_level="demo-inspected",
        sources=[
            src("https://github.com/harrymunro/beadsort", "repo", "Public repo; description verified via GitHub API 2026-09-17", "harrymunro", "2026-09-18"),
        ],
        repo_url="https://github.com/harrymunro/beadsort",
        install_url="https://github.com/harrymunro/beadsort",
        caveats="0 stars at check time; launch-week. Source tree not fully walked in this sweep.",
        readiness="runnable-from-readme",
    ),
    entry(
        id="jevmeter",
        title="JEVMETER",
        category="action-taking",
        short_description="Score transcript sentences on debate/earnings/podcast presets, then render an edited video.",
        actual_actions_or_outcome="CLI wizard writes a .jevmeter.mp4.",
        jev_role="Per-sentence scoring after transcription",
        other_components=["local video pipeline"],
        origin="community",
        evidence_level="demo-inspected",
        sources=[
            src("https://github.com/ChetasLua/jevmeter", "repo", "Repo exists; README wizard described in GitHub lane", "ChetasLua", "2026-09-17"),
        ],
        repo_url="https://github.com/ChetasLua/jevmeter",
        install_url="https://github.com/ChetasLua/jevmeter",
        caveats="Audio is transcribed then scored as text. Jev is not a native audio model. Accuracy badges are author claims.",
        readiness="runnable-from-readme",
    ),
    entry(
        id="blink-code-search",
        title="blink",
        category="action-taking",
        short_description="Filesystem walkers plus Jev scoring of which files match a natural-language query.",
        actual_actions_or_outcome="CLI table of paths with percentages.",
        jev_role="Relevance scoring of candidate files",
        other_components=["Bun"],
        origin="community",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/ellipsis-dev/blink", "repo", "README CLI example", "ellipsis-dev", "2026-09-16"),
        ],
        repo_url="https://github.com/ellipsis-dev/blink",
        install_url="https://github.com/ellipsis-dev/blink",
        caveats="Prototype search, not an index. May issue many parallel Jev calls.",
        readiness="runnable-from-readme",
    ),
    entry(
        id="neo4jev",
        title="neo4jev",
        category="action-taking",
        short_description="Walk a Neo4j graph by classifying neighboring relationships with Jev.",
        actual_actions_or_outcome="Graph navigation demo: classifier over edge types / neighbors.",
        jev_role="Choice over neighboring relationships",
        other_components=["Neo4j"],
        origin="community",
        evidence_level="demo-inspected",
        sources=[
            src("https://github.com/jexp/neo4jev", "repo", "GitHub description verified 2026-09-17", "jexp", "2026-09-17"),
        ],
        repo_url="https://github.com/jexp/neo4jev",
        install_url="https://github.com/jexp/neo4jev",
        caveats="Small demo (6 stars). README not fully re-read in the owner pass.",
        readiness="runnable-from-readme",
    ),
    entry(
        id="semdecide",
        title="semdecide",
        category="action-taking",
        short_description="Typed semantic decisions for Unix pipelines and CI.",
        actual_actions_or_outcome="CLI exit codes / JSON from Jev judgments on stdin or files.",
        jev_role="Native judgments on user-supplied text",
        other_components=["Unix pipeline"],
        origin="community",
        evidence_level="demo-inspected",
        sources=[
            src("https://github.com/sharziki/semdecide", "repo", "GitHub description verified", "sharziki", "2026-09-16"),
        ],
        repo_url="https://github.com/sharziki/semdecide",
        install_url="https://github.com/sharziki/semdecide",
        caveats="Small project. Do not treat as a standard library.",
        readiness="runnable-from-readme",
    ),
    entry(
        id="jev-router",
        title="jev-router",
        category="model-routing",
        highlight=True,
        short_description="Wraps Claude Code / Codex CLIs; Jev picks cheap vs strong model per user turn.",
        actual_actions_or_outcome="jev-claude / jev-codex launch real upstream CLIs with a routed model.",
        jev_role="Per-turn difficulty / model Choice",
        other_components=["Claude Code or Codex login", "Node"],
        origin="community",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/gargpratyush/jev-router", "repo", "README commands; 70 stars 2026-09-17", "gargpratyush", "2026-09-17"),
        ],
        repo_url="https://github.com/gargpratyush/jev-router",
        install_url="https://github.com/gargpratyush/jev-router",
        caveats="README uses JEV_API_KEY, not TYPESAFE_API_KEY. npm registry page was not separately opened.",
        readiness="installable-per-readme",
        skill_frameworks=["claude-code"],
    ),
    entry(
        id="jev-codex-router",
        title="Jev Codex Router",
        category="model-routing",
        short_description="Plugs into Codex Router: Jev classifies the turn, then code picks model/effort/tier.",
        actual_actions_or_outcome="Local jev_server.py with fail-open and a JSONL decision log.",
        jev_role="Turn classification plus routing policy in code",
        other_components=["Codex Router", "LiteLLM"],
        origin="community",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/0xNatoshi/jev-codex-router", "repo", "README architecture", "0xNatoshi", "2026-09-17"),
        ],
        repo_url="https://github.com/0xNatoshi/jev-codex-router",
        install_url="https://github.com/0xNatoshi/jev-codex-router",
        caveats="Backtest savings are author-measured. Fail-open means a Jev outage does not block coding.",
        readiness="runnable-from-readme",
    ),
    entry(
        id="skillranker",
        title="SkillRanker",
        category="model-routing",
        short_description="Rust CLI ranks which agent skill fits the next step from live session context.",
        actual_actions_or_outcome="sr demo (offline fixtures) or sr rank --allow-network; optional Claude Code hook.",
        jev_role="Skill ranking with abstention",
        other_components=["Claude Code hooks"],
        origin="community",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/Dicklesworthstone/skillranker", "repo", "README commands including offline demo", "Dicklesworthstone", "2026-09-17"),
        ],
        repo_url="https://github.com/Dicklesworthstone/skillranker",
        install_url="https://github.com/Dicklesworthstone/skillranker",
        caveats="Offline demo is fixtures. Live ranking needs a TypeSafe key.",
        readiness="runnable-from-readme",
        skill_frameworks=["claude-code-hooks"],
    ),
    entry(
        id="cookbook-skill-suggestion",
        title="Official skill-suggestion cookbook",
        category="model-routing",
        highlight=True,
        short_description="Two Jev requests rank 182 Hermes skills and may suggest none.",
        actual_actions_or_outcome="suggest() returns at most one skill name for the agent system prompt. Published table: wrong-skill loads 16.8% → 7.3% on a pinned Haiku run (author numbers).",
        jev_role="Choice over the roster plus Nouls for whether a skill is needed",
        other_components=["Hermes skill roster", "Anthropic agent under test"],
        origin="official",
        evidence_level="documented-example",
        sources=[
            src("https://docs.typesafe.ai/cookbooks/skill_suggestion.md", "docs", "Cookbook method, mermaid, published table, jev-1.12 / Haiku pin, rendered 2026-07-31", "TypeSafe", "2026-07-31"),
        ],
        demo_url="https://docs.typesafe.ai/cookbooks/skill_suggestion",
        install_url="https://docs.typesafe.ai/cookbooks/skill_suggestion.md",
        caveats="Numbers are TypeSafe's published eval, not reproduced here. Not a drop-in Hermes skill.",
        readiness="documented-example",
        skill_frameworks=["hermes"],
    ),
    entry(
        id="jev-agent-skill-router",
        title="Jev Agent Skill Router",
        category="model-routing",
        short_description="Python CLI/library: batched Jev Choice plus Noul gates route, no-skill, or review over a skill catalogue.",
        actual_actions_or_outcome="Returns a routing decision with call evidence. Does not load or execute skills. Author-recorded synthetic 72-case run versus a lexical baseline.",
        jev_role="Parallel Choice over catalogue batches; final Choice plus need, review, and per-candidate fit Nouls; Python applies thresholds",
        other_components=["stdlib HTTP", "synthetic catalogue fixtures"],
        origin="community",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/GodsBoy/jev-agent-skill-router", "repo", "README plus router.py, transport.py, policy.py; 3 stars; no skill execution", "GodsBoy", "2026-09-16"),
        ],
        repo_url="https://github.com/GodsBoy/jev-agent-skill-router",
        install_url="https://github.com/GodsBoy/jev-agent-skill-router#install-and-verify",
        caveats="Native x_search named this repo without a status citation; GitHub independently inspected. Benchmark is 24 synthetic skills / 72 requests, not a live Hermes catalogue. CLI name jev-router collides with gargpratyush/jev-router. 3 stars. Accuracy numbers are author-recorded, not re-run here.",
        readiness="runnable-from-readme",
        skill_frameworks=["hermes"],
    ),
    entry(
        id="email-jev-langgraph",
        title="Jev email intent workflow",
        category="email-routing",
        short_description="LangGraph demo: Jev Choice invoice vs general on mocked emails.",
        actual_actions_or_outcome="Prints intent, probabilities, and destination vs expected label. Does not send mail or pay invoices.",
        jev_role="Choice over two intents",
        other_components=["LangGraph", "typesafe_sdk", "mock JSON emails"],
        origin="community",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/GiesN/typesafe-jev-workflow", "repo", "README graph; tests mock the SDK", "GiesN", "2026-09-17"),
        ],
        repo_url="https://github.com/GiesN/typesafe-jev-workflow",
        install_url="https://github.com/GiesN/typesafe-jev-workflow",
        caveats="Smoke demo on 10 emails. Closest public analog to inbox triage; not a Hermes skill.",
        readiness="runnable-from-readme",
    ),
    entry(
        id="jev-mcp",
        title="Jev MCP (jkudish)",
        category="mcp",
        short_description="MCP tools: verify claims, screen content, rank candidates.",
        actual_actions_or_outcome="An MCP host receives typed verdicts from Jev.",
        jev_role="Native judgments via TypeSafe API",
        other_components=["npx", "MCP host"],
        origin="community",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/jkudish/jev-mcp", "repo", "README tools and npx install", "jkudish", "2026-09-17"),
        ],
        repo_url="https://github.com/jkudish/jev-mcp",
        install_url="https://github.com/jkudish/jev-mcp",
        caveats="Proof of concept. Several launch-week MCP clones exist; this is the one with inspected README. Author-claim catch examples.",
        readiness="installable",
        skill_frameworks=["mcp"],
    ),
    entry(
        id="typesafe-mcp",
        title="typesafe-mcp",
        category="mcp",
        short_description="Community MCP exposing TypeSafe System One to Claude / Codex.",
        actual_actions_or_outcome="Agent tools call Jev; host still executes side effects.",
        jev_role="Native API behind MCP tools",
        other_components=["MCP host"],
        origin="community",
        evidence_level="demo-inspected",
        sources=[
            src("https://github.com/itsmostafa/typesafe-mcp", "repo", "Repo exists; Reddit thread linked it", "itsmostafa", "2026-09-17"),
        ],
        repo_url="https://github.com/itsmostafa/typesafe-mcp",
        install_url="https://github.com/itsmostafa/typesafe-mcp",
        caveats="Not the official skill. Distinct from jkudish/jev-mcp and y0usaf/typesafe-mcp.",
        readiness="runnable-from-readme",
        skill_frameworks=["mcp"],
    ),
    entry(
        id="y0usaf-typesafe-mcp",
        title="y0usaf/typesafe-mcp",
        category="mcp",
        short_description="Thin MCP: one evaluate(state, questions) tool plus a typesafe://guide resource.",
        actual_actions_or_outcome="Host POSTs to api.typesafe.ai/v1/systemone; the agent still executes side effects.",
        jev_role="Native System One API behind a single MCP tool",
        other_components=["MCP host", "npx @y0usaf/typesafe-mcp"],
        origin="community",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/y0usaf/typesafe-mcp", "repo", "README plus index.js evaluate tool and HTTP client; 3 stars", "y0usaf", "2026-09-16"),
            src("https://x.com/realy0usaf/status/2100106949874335851", "tweet", "Author announced the repo", "realy0usaf", "2026-09-16"),
        ],
        repo_url="https://github.com/y0usaf/typesafe-mcp",
        install_url="https://github.com/y0usaf/typesafe-mcp#install",
        caveats="Launch-week MCP. Distinct from itsmostafa/typesafe-mcp and jkudish/jev-mcp. 3 stars. Not official.",
        readiness="installable-per-readme",
        skill_frameworks=["mcp"],
    ),
    entry(
        id="cookbook-function-calling",
        title="Official function-calling cookbook",
        category="official-cookbook",
        highlight=True,
        short_description="Map a natural-language trading request onto typed functions and closed-set arguments.",
        actual_actions_or_outcome="Dispatcher returns a function name plus Literal arguments with confidence; ordinary Python functions run.",
        jev_role="Choice over tools and closed-set args; Nouls for whether an arg was stated",
        other_components=["cooksafe", "example trader.py"],
        origin="official",
        evidence_level="documented-example",
        sources=[
            src("https://docs.typesafe.ai/cookbooks/function_calling.md", "docs", "Worked examples and Dispatcher description", "TypeSafe"),
        ],
        demo_url="https://docs.typesafe.ai/cookbooks/function_calling",
        install_url="https://docs.typesafe.ai/cookbooks/function_calling.md",
        caveats="Uses cached cookbook results unless you delete json_cache.json. Example domain is market data plots, not live brokerage.",
        readiness="documented-example",
    ),
    entry(
        id="cookbook-guardrails",
        title="Official LLM guardrails cookbook",
        category="official-cookbook",
        short_description="One TypeSafe request screens an LLM input or output for hazards, then code routes pass/review/block/support.",
        actual_actions_or_outcome="guard() returns a policy action. Does not send the user message itself.",
        jev_role="Nouls per hazard plus a harm Score",
        other_components=["cooksafe"],
        origin="official",
        evidence_level="documented-example",
        sources=[
            src("https://docs.typesafe.ai/cookbooks/llm_guardrails.md", "docs", "Cookbook flowchart and routing policy", "TypeSafe"),
        ],
        demo_url="https://docs.typesafe.ai/cookbooks/llm_guardrails",
        install_url="https://docs.typesafe.ai/cookbooks/llm_guardrails.md",
        caveats="Thresholds are yours. Cached published run unless you go live.",
        readiness="documented-example",
    ),
    entry(
        id="cookbook-citation-check",
        title="Official citation-check cookbook",
        category="official-cookbook",
        short_description="Check whether a quote's context supports a claim.",
        actual_actions_or_outcome="Choice plus confidence can flag a citation for human review.",
        jev_role="Choice: supports / does not support / uncertain",
        origin="official",
        evidence_level="documented-example",
        sources=[
            src("https://docs.typesafe.ai/cookbooks/citation_check.md", "docs", "Listed in llms.txt with method summary", "TypeSafe"),
        ],
        demo_url="https://docs.typesafe.ai/cookbooks/citation_check",
        install_url="https://docs.typesafe.ai/cookbooks/citation_check.md",
        caveats="Cookbook page listed in the official index; not fully re-read beyond the index blurb in this owner pass.",
        readiness="documented-example",
    ),
    entry(
        id="pattern-intent-routing",
        title="Official intent-routing pattern",
        category="official-cookbook",
        short_description="Classify a request, then code routes to deterministic logic, a specialist LLM, or a human.",
        actual_actions_or_outcome="Example ticket router uses intent Choice and complexity Score with confidence gates.",
        jev_role="Intent Choice and complexity Score",
        origin="official",
        evidence_level="documented-example",
        sources=[
            src("https://docs.typesafe.ai/patterns/intent-routing.md", "docs", "Python routing snippet extracted", "TypeSafe"),
        ],
        demo_url="https://docs.typesafe.ai/patterns/intent-routing",
        install_url="https://docs.typesafe.ai/patterns/intent-routing.md",
        caveats="Pattern, not a packaged product.",
        readiness="documented-example",
    ),
    entry(
        id="official-sdk-python",
        title="TypeSafe Python SDK",
        category="official-sdk",
        short_description="Official sync/async client for POST /v1/systemone.",
        actual_actions_or_outcome="TypeSafeClient.system_one returns typed Choice/Noul/Score answers for your code to branch on.",
        jev_role="Native System One model behind the SDK",
        other_components=["httpx", "msgspec"],
        origin="official",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/typesafe-ai/typesafe-sdk-python", "repo", "README + pyproject; PyPI typesafe-sdk 0.6.0", "typesafe-ai", "2026-09-15"),
            src("https://pypi.org/project/typesafe-sdk/0.6.0/", "pypi", "Version 0.6.0", "TypeSafe AI", "2026-09-15"),
        ],
        repo_url="https://github.com/typesafe-ai/typesafe-sdk-python",
        install_url="https://pypi.org/project/typesafe-sdk/",
        caveats="Needs TYPESAFE_API_KEY. Text-only API.",
        readiness="installable",
    ),
    entry(
        id="official-sdk-js",
        title="TypeSafe JavaScript SDK",
        category="official-sdk",
        short_description="Official TypeScript/JavaScript client with inferred answer types.",
        actual_actions_or_outcome="examples/demo.ts classifies a billing ticket with noul/choice/score.",
        jev_role="Native",
        other_components=["Node >=20"],
        origin="official",
        evidence_level="demo-inspected",
        sources=[
            src("https://github.com/typesafe-ai/typesafe-sdk-js", "repo", "examples/demo.ts; npm @typesafe-ai/sdk 0.6.0", "typesafe-ai", "2026-09-15"),
        ],
        repo_url="https://github.com/typesafe-ai/typesafe-sdk-js",
        demo_url="https://github.com/typesafe-ai/typesafe-sdk-js/blob/main/examples/demo.ts",
        install_url="https://www.npmjs.com/package/@typesafe-ai/sdk",
        caveats="Live demo needs TYPESAFE_API_KEY.",
        readiness="installable",
    ),
    entry(
        id="official-system-one-adapter",
        title="System One Adapter (Python)",
        category="official-sdk",
        short_description="Drop-in TypeSafeClient.system_one backed by OpenAI/Anthropic instead of Jev.",
        actual_actions_or_outcome="Same typed questions; LLM structured output for A/B comparison.",
        jev_role="None (LLM stand-in)",
        other_components=["openai extra", "anthropic extra", "typesafe-sdk types"],
        origin="official",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/typesafe-ai/system-one-adapter-python", "repo", "README + PyPI system-one-adapter 0.1.4", "typesafe-ai", "2026-09-16"),
        ],
        repo_url="https://github.com/typesafe-ai/system-one-adapter-python",
        install_url="https://pypi.org/project/system-one-adapter/",
        caveats="Explicitly not Jev. Cassette tests block network by default.",
        readiness="installable",
    ),
    entry(
        id="official-docs",
        title="TypeSafe documentation",
        category="official-docs",
        short_description="Live docs: System One programming model, primitives, API, cookbooks, demos.",
        actual_actions_or_outcome="Source of truth for contracts. llms.txt indexes every page.",
        jev_role="Documents Jev as jev-latest / text-only",
        origin="official",
        evidence_level="documented-example",
        sources=[
            src("https://docs.typesafe.ai/llms.txt", "docs", "Full index including cookbooks and API", "TypeSafe", CHECKED),
            src("https://docs.typesafe.ai/concepts/system-one.md", "docs", "Text-only; no images/audio/video yet", "TypeSafe", CHECKED),
            src("https://docs.typesafe.ai/api.md", "docs", "POST /v1/systemone", "TypeSafe", CHECKED),
        ],
        demo_url="https://docs.typesafe.ai/llms.txt",
        install_url="https://docs.typesafe.ai/introduction/quickstart.md",
        caveats="Mintlify .md paths. cookbooks.md URL served a specific cookbook, not an index, in this sweep.",
        readiness="docs",
    ),
    entry(
        id="official-skills",
        title="Official TypeSafe agent skill",
        category="official-docs",
        short_description="SKILL.md teaching agents to design System One workflows from live docs.",
        actual_actions_or_outcome="Agent writes SDK code; the skill itself does not call Jev.",
        jev_role="Design-time guidance",
        other_components=["Claude Code plugin marketplace", "skills.sh"],
        origin="official",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/typesafe-ai/skills", "repo", "SKILL.md frontmatter, marketplace.json, plugin 0.5.7", "typesafe-ai", "2026-09-12"),
            src("https://docs.typesafe.ai/agent-skill.md", "docs", "Install commands for Claude plugin and npx skills add", "TypeSafe", CHECKED),
        ],
        repo_url="https://github.com/typesafe-ai/skills",
        install_url="https://docs.typesafe.ai/agent-skill#installation",
        caveats="Not an inference wrapper. Keep live docs as source of truth.",
        readiness="installable",
        skill_frameworks=["claude-code", "skills.sh", "hermes"],
    ),
    entry(
        id="official-launch-blog",
        title="Introducing System One Models and Jev",
        category="official-docs",
        short_description="Launch post (2026-09-15): RLCD, pricing, workflow evals, Doom and Wikipedia-race videos.",
        actual_actions_or_outcome="Documents launch demos where game/page state is text/JSON and code issues actions.",
        jev_role="Judgments inside a harness; code owns the controller / browser",
        origin="official",
        evidence_level="author-claim",
        sources=[
            src("https://typesafe.ai/blog/introducing-system-one-models-and-jev", "article", "Launch article extracted; Doom/wiki videos; pricing $0.042/MTok input attributed to TypeSafe", "Diogo Almeida", "2026-09-15"),
            src("https://www.theregister.com/ai-and-ml/2026/09/16/typesafe-ai-debuts-model-for-machines-that-plays-doom/5296711", "article", "Independent press recap of Doom-shaped demo", "Thomas Claburn", "2026-09-16"),
        ],
        demo_url="https://typesafe.ai/blog/introducing-system-one-models-and-jev",
        caveats="Doom/Wiki harnesses are not in the public typesafe-ai GitHub org. Speed/cost/eval charts are vendor-published, not remeasured. HN discussion: https://news.ycombinator.com/item?id=49717558",
        readiness="documented-launch",
    ),
    entry(
        id="demo-smart-home",
        title="Smart home assistant demo",
        category="official-docs",
        short_description="Official demo: evaluate smart-home requests with speculative questions and LLM fallback.",
        actual_actions_or_outcome="Demo code decides device intents; Loom walkthrough. Not a physical home integration in the public org.",
        jev_role="Speculative questions over a user request",
        origin="official",
        evidence_level="documented-example",
        sources=[
            src("https://docs.typesafe.ai/demos/smart-home.md", "docs", "Page exists with Loom embed", "TypeSafe", CHECKED),
            src("https://docs.typesafe.ai/demos.md", "docs", "Only official interactive demo listed", "TypeSafe", CHECKED),
        ],
        demo_url="https://docs.typesafe.ai/demos/smart-home",
        install_url="https://docs.typesafe.ai/demos/smart-home.md",
        caveats="Did not download the Loom. Distinguish from production home automation.",
        readiness="documented-example",
    ),
    entry(
        id="vercel-ai-gateway-jev",
        title="Vercel AI Gateway + AI SDK evaluate",
        category="platform-integration",
        highlight=True,
        short_description="Jev available as typesafe-ai/jev on AI Gateway; AI SDK 7 experimental_evaluate.",
        actual_actions_or_outcome="evaluate() returns typed answers; example routes a support case. ZDR/no-training flags documented.",
        jev_role="Native evaluation model via Gateway",
        other_components=["Vercel AI Gateway", "AI SDK 7"],
        origin="platform",
        evidence_level="documented-example",
        sources=[
            src("https://vercel.com/changelog/typesafe-ai-jev-now-available-on-ai-gateway", "docs", "Changelog install snippet and model id", "Vercel", CHECKED),
            src("https://ai-sdk.dev/docs/ai-sdk-core/evaluation", "docs", "experimental_evaluate contract and example tree", "Vercel", CHECKED),
        ],
        demo_url="https://ai-sdk.dev/docs/ai-sdk-core/evaluation",
        install_url="https://vercel.com/ai-gateway/models/jev",
        caveats="API is experimental. TypeSafe workflow-eval multipliers in the changelog are vendor-attributed.",
        readiness="installable",
    ),
    entry(
        id="ruby-llm-typesafe",
        title="ruby_llm-typesafe",
        category="community-sdk",
        short_description="TypeSafe structured-output provider for RubyLLM 2.",
        actual_actions_or_outcome="Ruby apps can ask System One questions through RubyLLM.",
        jev_role="Native via TypeSafe API",
        other_components=["RubyLLM 2"],
        origin="community",
        evidence_level="demo-inspected",
        sources=[
            src("https://github.com/kieranklaassen/ruby_llm-typesafe", "repo", "Repo exists; X launch mention", "kieranklaassen", "2026-09-16"),
        ],
        repo_url="https://github.com/kieranklaassen/ruby_llm-typesafe",
        install_url="https://github.com/kieranklaassen/ruby_llm-typesafe",
        caveats="Unofficial. Small star count.",
        readiness="installable-per-readme",
    ),
    entry(
        id="typesafeai-net",
        title="TypeSafeAI.Net",
        category="community-sdk",
        short_description="Unofficial .NET SDK for TypeSafe AI.",
        actual_actions_or_outcome=".NET clients call System One.",
        jev_role="Native via TypeSafe API",
        other_components=[".NET"],
        origin="community",
        evidence_level="demo-inspected",
        sources=[
            src("https://github.com/Hawxy/TypeSafeAI.Net", "repo", "Live repo; Hawxy/TypeSafe.Sdk 404", "Hawxy", "2026-09-17"),
        ],
        repo_url="https://github.com/Hawxy/TypeSafeAI.Net",
        install_url="https://github.com/Hawxy/TypeSafeAI.Net",
        caveats="Unofficial. Older TypeSafe.Sdk URL is dead.",
        readiness="installable-per-readme",
    ),
    entry(
        id="building-with-jev-skill",
        title="building-with-jev skill",
        category="agent-skill",
        short_description="Community skill for writing Jev programs (Claude plugin + skills.sh).",
        actual_actions_or_outcome="Guides question design; does not execute Jev unless the agent writes code.",
        jev_role="Design-time",
        origin="community",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/dbreunig/building-with-jev-skill", "repo", "SKILL.md frontmatter name=jev; plugin 0.1.0", "dbreunig", "2026-09-17"),
        ],
        repo_url="https://github.com/dbreunig/building-with-jev-skill",
        install_url="https://github.com/dbreunig/building-with-jev-skill",
        caveats="Overlaps the official typesafe-ai skill.",
        readiness="installable",
        skill_frameworks=["claude-code", "skills.sh"],
    ),
    entry(
        id="jev-axi",
        title="jev-axi",
        category="agent-skill",
        short_description="CLI + skill for log triage, diff review, untrusted-text screen, ranking.",
        actual_actions_or_outcome="Shell commands return probabilities; hooks can block commands.",
        jev_role="Narrow judgments on user-supplied text",
        other_components=["Node 22+", "npm jev-axi"],
        origin="community",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/shiftynick/jev-axi", "repo", "SKILL.md frontmatter compatibility line + npm install -g jev-axi", "shiftynick", "2026-09-17"),
        ],
        repo_url="https://github.com/shiftynick/jev-axi",
        install_url="https://github.com/shiftynick/jev-axi",
        caveats="Latency/cost sentences in the skill body are author claims. Fails closed if the key is missing.",
        readiness="installable",
        skill_frameworks=["agent-skillmd"],
    ),
    entry(
        id="advocaat",
        title="advocaat",
        category="agent-skill",
        short_description="Small TypeScript ask() client plus an agent skill over Jev.",
        actual_actions_or_outcome="Typed answers under question keys in one request.",
        jev_role="Native",
        other_components=["optional Vercel AI Gateway"],
        origin="community",
        evidence_level="code-inspected",
        sources=[
            src("https://github.com/pithings/advocaat", "repo", "README + SKILL.md + npx skills add pithings/advocaat", "pithings", "2026-09-18"),
        ],
        repo_url="https://github.com/pithings/advocaat",
        install_url="https://github.com/pithings/advocaat",
        caveats="Wrapper, not a new model.",
        readiness="installable",
        skill_frameworks=["skills.sh"],
    ),
    entry(
        id="list-anil-matcha",
        title="awesome-jev-by-typesafe (Anil-matcha)",
        category="awesome-list",
        short_description="Largest-star independent Jev list with examples and prompts.",
        actual_actions_or_outcome="Curation plus examples/python and examples/typescript.",
        jev_role="n/a (list)",
        origin="community",
        evidence_level="demo-inspected",
        sources=[
            src("https://github.com/Anil-matcha/awesome-jev-by-typesafe", "repo", "README + examples dirs; 407 stars 2026-09-17; unaffiliated disclaimer", "Anil-matcha", "2026-09-17"),
        ],
        repo_url="https://github.com/Anil-matcha/awesome-jev-by-typesafe",
        caveats="Vendor latency/price cited from TypeSafe docs. Neighboring sibling lists by the same author are not Jev-only.",
        readiness="list",
    ),
    entry(
        id="list-abdelstark",
        title="awesome-typesafe (AbdelStark)",
        category="awesome-list",
        short_description="Structured official + community directory with an independent disclaimer.",
        actual_actions_or_outcome="List + GitHub Pages site.",
        jev_role="n/a (list)",
        origin="community",
        evidence_level="demo-inspected",
        sources=[
            src("https://github.com/AbdelStark/awesome-typesafe", "repo", "README inspected", "AbdelStark", "2026-09-17"),
        ],
        repo_url="https://github.com/AbdelStark/awesome-typesafe",
        demo_url="https://abdelstark.github.io/awesome-typesafe/",
        caveats="Name collides with unrelated TypeScript 'typesafe' lists.",
        readiness="list",
    ),
    entry(
        id="list-yibie",
        title="awesome-jev (yibie)",
        category="awesome-list",
        short_description="Category field guide that requires actual Jev use.",
        actual_actions_or_outcome="Per-category markdown files.",
        jev_role="n/a (list)",
        origin="community",
        evidence_level="demo-inspected",
        sources=[
            src("https://github.com/yibie/awesome-jev", "repo", "README category counts 2026-09-17", "yibie", "2026-09-17"),
        ],
        repo_url="https://github.com/yibie/awesome-jev",
        caveats="Smaller than auto-generated directories; inclusion criteria are stricter.",
        readiness="list",
    ),
    entry(
        id="list-anotia",
        title="awesome-jev (AnotiaWang)",
        category="awesome-list",
        short_description="Bilingual EN/ZH awesome list (CC0).",
        actual_actions_or_outcome="Curation across SDKs, apps, cookbooks.",
        jev_role="n/a (list)",
        origin="community",
        evidence_level="demo-inspected",
        sources=[
            src("https://github.com/AnotiaWang/awesome-jev", "repo", "README; CC0-1.0", "AnotiaWang", "2026-09-18"),
        ],
        repo_url="https://github.com/AnotiaWang/awesome-jev",
        caveats="Launch-week overlap with other lists.",
        readiness="list",
    ),
    entry(
        id="list-hellogumbo",
        title="awesome-jev (hellogumbo)",
        category="awesome-list",
        short_description="Directory claiming hundreds of entries plus awesomejev.com.",
        actual_actions_or_outcome="Broad directory. Treat claimed counts as catalog size, not unique production apps.",
        jev_role="n/a (list)",
        origin="community",
        evidence_level="author-claim",
        sources=[
            src("https://github.com/hellogumbo/awesome-jev", "repo", "README claims 410 entries as of 2026-09-17", "hellogumbo", "2026-09-18"),
        ],
        repo_url="https://github.com/hellogumbo/awesome-jev",
        demo_url="https://awesomejev.com",
        caveats="Largest claimed entry count in this sweep. Many items are thin wrappers. Not treated as verified unique apps.",
        readiness="list",
    ),
    entry(
        id="list-rhc98",
        title="awesome-jev (rhc98)",
        category="awesome-list",
        short_description="Auto-judged catalog: README says Jev curated the list.",
        actual_actions_or_outcome="Listed repos according to a Jev policy, not a human review.",
        jev_role="Inclusion classifier (meta)",
        origin="community",
        evidence_level="author-claim",
        sources=[
            src("https://github.com/rhc98/awesome-jev", "repo", "README badges judged 579 / listed 369", "rhc98", "2026-09-17"),
        ],
        repo_url="https://github.com/rhc98/awesome-jev",
        demo_url="https://awesome-jev.xyz",
        caveats="Do not copy wholesale. Inclusion is a model output.",
        readiness="list",
    ),
    entry(
        id="openjev",
        title="OpenJev",
        category="related-not-jev",
        short_description="Community open-weight attempt at the System One shape. Not api.typesafe.ai.",
        actual_actions_or_outcome="Local model / site. Not official Jev.",
        jev_role="none (reproduction)",
        origin="related",
        evidence_level="author-claim",
        sources=[
            src("https://github.com/TheoLeeCJ/openjev", "repo", "822 stars 2026-09-17; description is a local analog", "TheoLeeCJ", "2026-09-16"),
        ],
        repo_url="https://github.com/TheoLeeCJ/openjev",
        demo_url="https://openjev.com",
        caveats="Not TypeSafe Jev. Do not list as an official integration.",
        readiness="related-not-jev-api",
    ),
    entry(
        id="jevlike",
        title="jevlike",
        category="related-not-jev",
        short_description="Another community reproduction of the System One interface.",
        actual_actions_or_outcome="Local analog, not the TypeSafe API.",
        jev_role="none (reproduction)",
        origin="related",
        evidence_level="author-claim",
        sources=[
            src("https://github.com/vinnylarouge/jevlike", "repo", "680 stars 2026-09-17; README not fully inspected", "vinnylarouge", "2026-09-16"),
        ],
        repo_url="https://github.com/vinnylarouge/jevlike",
        caveats="Not official Jev. Listed only so people do not confuse it with TypeSafe.",
        readiness="related-not-jev-api",
    ),
    entry(
        id="jevmlx",
        title="jevmlx",
        category="related-not-jev",
        short_description="Jev-style parallel constrained decisions for MLX models on Apple Silicon.",
        actual_actions_or_outcome="Local MLX forward pass, not TypeSafe weights.",
        jev_role="none (local analog)",
        origin="related",
        evidence_level="demo-inspected",
        sources=[
            src("https://github.com/bnsd55/jevmlx", "repo", "GitHub description verified", "bnsd55", "2026-09-17"),
        ],
        repo_url="https://github.com/bnsd55/jevmlx",
        caveats="Not Jev weights. Useful as an offline comparison, not a TypeSafe client.",
        readiness="related-not-jev-api",
    ),
]


def by(login: str, display: str, **extra) -> dict:
    item = {
        "creator_display": display,
        "creator_url": f"https://github.com/{login}",
        "credit_kind": "by",
    }
    item.update(extra)
    return item


def maintained(login: str, display: str, **extra) -> dict:
    item = {
        "creator_display": display,
        "creator_url": extra.pop("creator_url", f"https://github.com/{login}"),
        "credit_kind": "maintained-by",
    }
    item.update(extra)
    return item


# Public GitHub profile names when they are a full name; otherwise @login.
# Orgs use maintained-by. First-name-only GitHub names stay as @login.
CREDITS = {
    "jev-ultrafast": maintained("browser-use", "Browser Use"),
    "typesafe-mario": by("fhshaik", "@fhshaik"),
    "typesafe-computer-use": by("awlevin", "Aaron Levin"),
    "jev-review": by("devagrawal09", "Dev Agrawal"),
    "pg-jev": by("realZachi", "@realZachi"),
    "pi-warden": by("DevMortimer", "Ryan Joshua"),
    "foreman": maintained("thruwire", "ThruWire"),
    "beadsort": by("harrymunro", "Harry Munro"),
    "jevmeter": by("ChetasLua", "Chetas Lua"),
    "blink-code-search": maintained("ellipsis-dev", "ellipsis.dev"),
    "neo4jev": by("jexp", "Michael Hunger"),
    "semdecide": by("sharziki", "Sharvil Saxena"),
    "jev-router": by("gargpratyush", "Pratyush Garg"),
    "jev-codex-router": by("0xNatoshi", "@0xNatoshi"),
    "skillranker": by("Dicklesworthstone", "Jeff Emanuel"),
    "cookbook-skill-suggestion": maintained("typesafe-ai", "TypeSafe AI"),
    "jev-agent-skill-router": by("GodsBoy", "Dewaldt Huysamen"),
    "email-jev-langgraph": by("GiesN", "@GiesN"),
    "jev-mcp": by("jkudish", "Joey Kudish"),
    "typesafe-mcp": by("itsmostafa", "@itsmostafa"),
    "y0usaf-typesafe-mcp": by(
        "y0usaf",
        "Sami Ansari",
        also_credits=[
            {
                "label": "Announced by",
                "display": "@realy0usaf",
                "url": "https://x.com/realy0usaf",
            }
        ],
    ),
    "cookbook-function-calling": maintained("typesafe-ai", "TypeSafe AI"),
    "cookbook-guardrails": maintained("typesafe-ai", "TypeSafe AI"),
    "cookbook-citation-check": maintained("typesafe-ai", "TypeSafe AI"),
    "pattern-intent-routing": maintained("typesafe-ai", "TypeSafe AI"),
    "official-sdk-python": maintained("typesafe-ai", "TypeSafe AI"),
    "official-sdk-js": maintained("typesafe-ai", "TypeSafe AI"),
    "official-system-one-adapter": maintained("typesafe-ai", "TypeSafe AI"),
    "official-docs": maintained("typesafe-ai", "TypeSafe AI"),
    "official-skills": maintained("typesafe-ai", "TypeSafe AI"),
    "official-launch-blog": maintained(
        "typesafe-ai",
        "TypeSafe AI",
        named_creator="Diogo Almeida",
        creator_url="https://github.com/typesafe-ai",
    ),
    "demo-smart-home": maintained("typesafe-ai", "TypeSafe AI"),
    "vercel-ai-gateway-jev": maintained("vercel", "Vercel"),
    "ruby-llm-typesafe": by("kieranklaassen", "Kieran Klaassen"),
    "typesafeai-net": by("Hawxy", "@Hawxy"),
    "building-with-jev-skill": by("dbreunig", "Drew Breunig"),
    "jev-axi": by("shiftynick", "Nicholas Underwood"),
    "advocaat": maintained("pithings", "PiThings"),
    "list-anil-matcha": by("Anil-matcha", "Anil Chandra Naidu Matcha"),
    "list-abdelstark": by("AbdelStark", "@AbdelStark"),
    "list-yibie": by("yibie", "@yibie"),
    "list-anotia": by("AnotiaWang", "Andy Wang"),
    "list-hellogumbo": maintained("hellogumbo", "GUMBO"),
    "list-rhc98": by("rhc98", "@rhc98"),
    "openjev": by("TheoLeeCJ", "Theodore Lee"),
    "jevlike": by("vinnylarouge", "@vinnylarouge"),
    "jevmlx": by("bnsd55", "@bnsd55"),
}

PROSE = {
    "jev-ultrafast": {
        "short_description": "Uses Jev to pick the next browser operation and target from an indexed DOM; a small LLM only types text.",
        "actual_actions_or_outcome": "Drives Chrome through a local inspector. The README documents a Google Flights search example. It does not book flights.",
        "jev_role": "Choice of operation plus speculative target questions in one request",
        "caveats": "Timing and cost claims in the README were not remeasured. Jev is text-only; the page is serialized to text/DOM, not pixels.",
    },
    "typesafe-mario": {
        "short_description": "Uses Jev to choose NES controller macros from emulator RAM JSON, not screenshots.",
        "actual_actions_or_outcome": "Local play loop writes run JSONL. A dashboard shows action distribution.",
        "jev_role": "Choice over legal controller actions",
        "caveats": "The ROM is not in the repo. Interactive demo, not a shipped product. No native vision.",
    },
    "typesafe-computer-use": {
        "short_description": "OCRs a Mac screen, then Jev chooses the next UI action and the code clicks.",
        "actual_actions_or_outcome": "Local screenshot → OCR → Choice/Noul → OS action loop.",
        "jev_role": "Action selection on OCR text state",
        "caveats": "Not native vision. Per-step cost in the GitHub description is an author claim.",
    },
    "jev-review": {
        "short_description": "Runs staged Jev judgments over git diffs or a local codebase and shows them on a dashboard.",
        "actual_actions_or_outcome": "JSON reports plus a dashboard on 127.0.0.1:4317. Does not publish reviews remotely.",
        "jev_role": "Noul risk matrix, Choice/Score file profiles, evidence selection, severity routing",
        "caveats": "Developer tool, not a hosted CI product. Thresholds are code policy.",
    },
    "pg-jev": {
        "short_description": "PostgreSQL helpers that filter, sort, or classify rows with Jev.",
        "actual_actions_or_outcome": "SQL helpers call TypeSafe. Rows that match a Noul, Choice, or Score filter are returned by the database.",
        "jev_role": "Batched parallel Noul/Choice/Score per row",
        "caveats": "Needs untrusted plpython3u / superuser. Row text is sent to TypeSafe. Latency numbers in the README were not re-run.",
    },
    "pi-warden": {
        "short_description": "Asks Jev whether a Pi agent tool call is irreversible or off-task before it runs.",
        "actual_actions_or_outcome": "Steers or blocks Pi tool calls. Published as a pi.dev package.",
        "jev_role": "Judgments on proposed tool calls, stuck loops, unverified done claims",
        "caveats": "Did not re-run against a live Pi session.",
    },
    "foreman": {
        "short_description": "Uses the official Python SDK so a software-factory supervisor can judge worker steps.",
        "actual_actions_or_outcome": "Semantic supervision of coding workers (per README/description).",
        "jev_role": "Noul/judgments via AsyncTypeSafeClient",
        "caveats": "Full README walkthrough was partial; grounded on import evidence and description.",
    },
    "beadsort": {
        "short_description": "Uses Jev to label beads issues from their text.",
        "actual_actions_or_outcome": "Writes labels onto beads items from issue text.",
        "jev_role": "Classification / labeling Choice or Noul over issue state",
        "caveats": "0 stars at check time; launch-week. Source tree not fully walked in this sweep.",
    },
    "jevmeter": {
        "short_description": "Scores transcript sentences with Jev, then renders an edited video.",
        "actual_actions_or_outcome": "CLI wizard writes a .jevmeter.mp4.",
        "jev_role": "Per-sentence scoring after transcription",
        "caveats": "Audio is transcribed then scored as text. Jev is not a native audio model. Accuracy badges are author claims.",
    },
    "blink-code-search": {
        "short_description": "Walks the filesystem and uses Jev to score which files match a natural-language query.",
        "actual_actions_or_outcome": "CLI table of paths with percentages.",
        "jev_role": "Relevance scoring of candidate files",
        "caveats": "Prototype search, not an index. May issue many parallel Jev calls.",
    },
    "neo4jev": {
        "short_description": "Walks a Neo4j graph by asking Jev which neighboring relationship to follow.",
        "actual_actions_or_outcome": "Graph navigation demo: classifier over edge types / neighbors.",
        "jev_role": "Choice over neighboring relationships",
        "caveats": "Small demo (6 stars). README not fully re-read in the owner pass.",
    },
    "semdecide": {
        "short_description": "Turns Jev judgments into Unix pipeline exit codes or JSON.",
        "actual_actions_or_outcome": "CLI exit codes / JSON from Jev judgments on stdin or files.",
        "jev_role": "Native judgments on user-supplied text",
        "caveats": "Small project. Do not treat as a standard library.",
    },
    "jev-router": {
        "short_description": "Uses Jev to pick a model for each Claude Code or Codex request.",
        "actual_actions_or_outcome": "jev-claude / jev-codex launch real upstream CLIs with a routed model.",
        "jev_role": "Per-turn difficulty / model Choice",
        "caveats": "README uses JEV_API_KEY, not TYPESAFE_API_KEY. npm registry page was not separately opened.",
    },
    "jev-codex-router": {
        "short_description": "Classifies each Codex Router turn with Jev, then code picks model, effort, and tier.",
        "actual_actions_or_outcome": "Local jev_server.py with fail-open and a JSONL decision log.",
        "jev_role": "Turn classification plus routing policy in code",
        "caveats": "Backtest savings are author-measured. Fail-open means a Jev outage does not block coding.",
    },
    "skillranker": {
        "short_description": "Ranks which agent skill fits the next step from live session context.",
        "actual_actions_or_outcome": "sr demo (offline fixtures) or sr rank --allow-network; optional Claude Code hook.",
        "jev_role": "Skill ranking with abstention",
        "caveats": "Offline demo is fixtures. Live ranking needs a TypeSafe key.",
    },
    "cookbook-skill-suggestion": {
        "short_description": "Two Jev requests rank 182 Hermes skills and may suggest none.",
        "actual_actions_or_outcome": "suggest() returns at most one skill name for the agent system prompt. Published table: wrong-skill loads 16.8% → 7.3% on a pinned Haiku run (author numbers).",
        "jev_role": "Choice over the roster plus Nouls for whether a skill is needed",
        "caveats": "Numbers are TypeSafe's published eval, not reproduced here. Not a drop-in Hermes skill.",
    },
    "jev-agent-skill-router": {
        "short_description": "Routes over a skill catalogue with Jev Choice and Noul gates; it does not load the skills.",
        "actual_actions_or_outcome": "Returns a routing decision with call evidence. Does not load or execute skills. Author-recorded synthetic 72-case run versus a lexical baseline.",
        "jev_role": "Parallel Choice over catalogue batches; final Choice plus need, review, and per-candidate fit Nouls; Python applies thresholds",
        "caveats": "Native x_search named this repo without a status citation; GitHub independently inspected. Benchmark is 24 synthetic skills / 72 requests, not a live Hermes catalogue. CLI name jev-router collides with gargpratyush/jev-router. 3 stars. Accuracy numbers are author-recorded, not re-run here.",
    },
    "email-jev-langgraph": {
        "short_description": "LangGraph demo that classifies mocked emails as invoice or general with Jev.",
        "actual_actions_or_outcome": "Prints intent, probabilities, and destination vs expected label. Does not send mail or pay invoices.",
        "jev_role": "Choice over two intents",
        "caveats": "Smoke demo on 10 emails. Closest public analog to inbox triage; not a Hermes skill.",
    },
    "jev-mcp": {
        "short_description": "MCP tools that verify claims, screen content, and rank candidates with Jev.",
        "actual_actions_or_outcome": "An MCP host receives typed verdicts from Jev.",
        "jev_role": "Native judgments via TypeSafe API",
        "caveats": "Proof of concept. Several launch-week MCP clones exist; this is the one with inspected README. Author-claim catch examples.",
    },
    "typesafe-mcp": {
        "short_description": "Community MCP that exposes TypeSafe System One to Claude or Codex.",
        "actual_actions_or_outcome": "Agent tools call Jev; the host still executes side effects.",
        "jev_role": "Native API behind MCP tools",
        "caveats": "Not the official skill. Distinct from jkudish/jev-mcp and y0usaf/typesafe-mcp.",
    },
    "y0usaf-typesafe-mcp": {
        "short_description": "One MCP evaluate(state, questions) tool that POSTs to the TypeSafe API.",
        "actual_actions_or_outcome": "Host POSTs to api.typesafe.ai/v1/systemone; the agent still executes side effects.",
        "jev_role": "Native System One API behind a single MCP tool",
        "caveats": "Launch-week MCP. Distinct from itsmostafa/typesafe-mcp and jkudish/jev-mcp. 3 stars. Not official.",
    },
    "cookbook-function-calling": {
        "short_description": "Maps a natural-language trading request onto typed functions and closed-set arguments.",
        "actual_actions_or_outcome": "Dispatcher returns a function name plus Literal arguments with confidence; ordinary Python functions run.",
        "jev_role": "Choice over tools and closed-set args; Nouls for whether an arg was stated",
        "caveats": "Uses cached cookbook results unless you delete json_cache.json. Example domain is market data plots, not live brokerage.",
    },
    "cookbook-guardrails": {
        "short_description": "Screens an LLM input or output for hazards, then code chooses pass, review, block, or support.",
        "actual_actions_or_outcome": "guard() returns a policy action. Does not send the user message itself.",
        "jev_role": "Nouls per hazard plus a harm Score",
        "caveats": "Thresholds are yours. Cached published run unless you go live.",
    },
    "cookbook-citation-check": {
        "short_description": "Checks whether a quote's context supports a claim.",
        "actual_actions_or_outcome": "Choice plus confidence can flag a citation for human review.",
        "jev_role": "Choice: supports / does not support / uncertain",
        "caveats": "Cookbook page listed in the official index; not fully re-read beyond the index blurb in this owner pass.",
    },
    "pattern-intent-routing": {
        "short_description": "Classifies a request, then code routes to deterministic logic, a specialist LLM, or a human.",
        "actual_actions_or_outcome": "Example ticket router uses intent Choice and complexity Score with confidence gates.",
        "jev_role": "Intent Choice and complexity Score",
        "caveats": "Pattern, not a packaged product.",
    },
    "official-sdk-python": {
        "short_description": "Official Python client for POST /v1/systemone.",
        "actual_actions_or_outcome": "TypeSafeClient.system_one returns typed Choice/Noul/Score answers for your code to branch on.",
        "jev_role": "Native System One model behind the SDK",
        "caveats": "Needs TYPESAFE_API_KEY. Text-only API.",
    },
    "official-sdk-js": {
        "short_description": "Official TypeScript/JavaScript client with inferred answer types.",
        "actual_actions_or_outcome": "examples/demo.ts classifies a billing ticket with noul/choice/score.",
        "jev_role": "Native",
        "caveats": "Live demo needs TYPESAFE_API_KEY.",
    },
    "official-system-one-adapter": {
        "short_description": "Drop-in TypeSafeClient.system_one backed by OpenAI or Anthropic instead of Jev.",
        "actual_actions_or_outcome": "Same typed questions; LLM structured output for A/B comparison.",
        "jev_role": "None (LLM stand-in)",
        "caveats": "Explicitly not Jev. Cassette tests block network by default.",
    },
    "official-docs": {
        "short_description": "Live docs for the System One model, primitives, API, cookbooks, and demos.",
        "actual_actions_or_outcome": "Source of truth for contracts. llms.txt indexes every page.",
        "jev_role": "Documents Jev as jev-latest / text-only",
        "caveats": "Mintlify .md paths. cookbooks.md URL served a specific cookbook, not an index, in this sweep.",
    },
    "official-skills": {
        "short_description": "SKILL.md that teaches agents to design System One workflows from the live docs.",
        "actual_actions_or_outcome": "Agent writes SDK code; the skill itself does not call Jev.",
        "jev_role": "Design-time guidance",
        "caveats": "Not an inference wrapper. Keep live docs as source of truth.",
    },
    "official-launch-blog": {
        "short_description": "Launch post (2026-09-15) covering RLCD, pricing, workflow evals, and Doom and Wikipedia-race videos.",
        "actual_actions_or_outcome": "Documents launch demos where game/page state is text/JSON and code issues actions.",
        "jev_role": "Judgments inside a harness; code owns the controller / browser",
        "caveats": "Doom/Wiki harnesses are not in the public typesafe-ai GitHub org. Speed/cost/eval charts are vendor-published, not remeasured. HN discussion: https://news.ycombinator.com/item?id=49717558",
    },
    "demo-smart-home": {
        "short_description": "Official demo that evaluates smart-home requests with speculative questions and an LLM fallback.",
        "actual_actions_or_outcome": "Demo code decides device intents; Loom walkthrough. Not a physical home integration in the public org.",
        "jev_role": "Speculative questions over a user request",
        "caveats": "Did not download the Loom. Distinguish from production home automation.",
    },
    "vercel-ai-gateway-jev": {
        "short_description": "Jev as typesafe-ai/jev on AI Gateway, plus AI SDK 7 experimental_evaluate.",
        "actual_actions_or_outcome": "evaluate() returns typed answers; example routes a support case. ZDR/no-training flags documented.",
        "jev_role": "Native evaluation model via Gateway",
        "caveats": "API is experimental. TypeSafe workflow-eval multipliers in the changelog are vendor-attributed.",
    },
    "ruby-llm-typesafe": {
        "short_description": "TypeSafe structured-output provider for RubyLLM 2.",
        "actual_actions_or_outcome": "Ruby apps can ask System One questions through RubyLLM.",
        "jev_role": "Native via TypeSafe API",
        "caveats": "Unofficial. Small star count.",
    },
    "typesafeai-net": {
        "short_description": "Unofficial .NET SDK for TypeSafe AI.",
        "actual_actions_or_outcome": ".NET clients call System One.",
        "jev_role": "Native via TypeSafe API",
        "caveats": "Unofficial. Older TypeSafe.Sdk URL is dead.",
    },
    "building-with-jev-skill": {
        "short_description": "Community skill for writing Jev programs (Claude plugin and skills.sh).",
        "actual_actions_or_outcome": "Guides question design; does not execute Jev unless the agent writes code.",
        "jev_role": "Design-time",
        "caveats": "Overlaps the official typesafe-ai skill.",
    },
    "jev-axi": {
        "short_description": "CLI and skill for log triage, diff review, untrusted-text screening, and ranking.",
        "actual_actions_or_outcome": "Shell commands return probabilities; hooks can block commands.",
        "jev_role": "Narrow judgments on user-supplied text",
        "caveats": "Latency/cost sentences in the skill body are author claims. Fails closed if the key is missing.",
    },
    "advocaat": {
        "short_description": "Small TypeScript ask() client plus an agent skill over Jev.",
        "actual_actions_or_outcome": "Typed answers under question keys in one request.",
        "jev_role": "Native",
        "caveats": "Wrapper, not a new model.",
    },
    "list-anil-matcha": {
        "short_description": "Independent Jev list with examples and prompts (highest star count among lists in this sweep).",
        "actual_actions_or_outcome": "Curation plus examples/python and examples/typescript.",
        "jev_role": "n/a (list)",
        "caveats": "Vendor latency/price cited from TypeSafe docs. Neighboring sibling lists by the same author are not Jev-only.",
    },
    "list-abdelstark": {
        "short_description": "Official plus community directory with an independent disclaimer.",
        "actual_actions_or_outcome": "List plus GitHub Pages site.",
        "jev_role": "n/a (list)",
        "caveats": "Name collides with unrelated TypeScript 'typesafe' lists.",
    },
    "list-yibie": {
        "short_description": "Category field guide that requires actual Jev use.",
        "actual_actions_or_outcome": "Per-category markdown files.",
        "jev_role": "n/a (list)",
        "caveats": "Smaller than auto-generated directories; inclusion criteria are stricter.",
    },
    "list-anotia": {
        "short_description": "Bilingual EN/ZH awesome list (CC0).",
        "actual_actions_or_outcome": "Curation across SDKs, apps, cookbooks.",
        "jev_role": "n/a (list)",
        "caveats": "Launch-week overlap with other lists.",
    },
    "list-hellogumbo": {
        "short_description": "Directory claiming hundreds of entries, plus awesomejev.com.",
        "actual_actions_or_outcome": "Broad directory. Treat claimed counts as catalog size, not unique production apps.",
        "jev_role": "n/a (list)",
        "caveats": "Largest claimed entry count in this sweep. Many items are thin wrappers. Not treated as verified unique apps.",
    },
    "list-rhc98": {
        "short_description": "Auto-judged catalog: README says Jev curated the list.",
        "actual_actions_or_outcome": "Listed repos according to a Jev policy, not a human review.",
        "jev_role": "Inclusion classifier (meta)",
        "caveats": "Do not copy wholesale. Inclusion is a model output.",
    },
    "openjev": {
        "short_description": "Community open-weight attempt at the System One shape. Not api.typesafe.ai.",
        "actual_actions_or_outcome": "Local model / site. Not official Jev.",
        "jev_role": "none (reproduction)",
        "caveats": "Not TypeSafe Jev. Do not list as an official integration.",
    },
    "jevlike": {
        "short_description": "Another community reproduction of the System One interface.",
        "actual_actions_or_outcome": "Local analog, not the TypeSafe API.",
        "jev_role": "none (reproduction)",
        "caveats": "Not official Jev. Listed only so people do not confuse it with TypeSafe.",
    },
    "jevmlx": {
        "short_description": "Jev-style parallel constrained decisions for MLX models on Apple Silicon.",
        "actual_actions_or_outcome": "Local MLX forward pass, not TypeSafe weights.",
        "jev_role": "none (local analog)",
        "caveats": "Not Jev weights. Useful as an offline comparison, not a TypeSafe client.",
    },
}


def apply_overlays(entries: list[dict]) -> None:
    ids = [e["id"] for e in entries]
    missing_c = [i for i in ids if i not in CREDITS]
    missing_p = [i for i in ids if i not in PROSE]
    extra_c = sorted(set(CREDITS) - set(ids))
    extra_p = sorted(set(PROSE) - set(ids))
    if missing_c or missing_p or extra_c or extra_p:
        raise SystemExit(
            f"overlay mismatch credits_missing={missing_c} prose_missing={missing_p} "
            f"credits_extra={extra_c} prose_extra={extra_p}"
        )
    for entry in entries:
        entry.update(CREDITS[entry["id"]])
        entry.update(PROSE[entry["id"]])


def main() -> None:
    ids = [e["id"] for e in ENTRIES]
    assert len(ids) == len(set(ids)), sorted(x for x in ids if ids.count(x) > 1)
    apply_overlays(ENTRIES)
    payload = {
        "schema_version": 1,
        "updated": CHECKED,
        "disclaimer": "Unofficial curated catalog. Not affiliated with TypeSafe AI. Benchmarks are attributed, not endorsed.",
        "entries": ENTRIES,
    }
    dest = ROOT / "data" / "use-cases.json"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"wrote {dest} n={len(ENTRIES)}")


if __name__ == "__main__":
    main()
